# Generated by Django 4.1.2 on 2023-08-15 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0002_remove_budgetaccount_id_school_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budgetitem',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='budget.budgetitem'),
        ),
    ]
