# Generated by Django 4.1.2 on 2023-08-22 16:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('budget', '0003_alter_budgetitem_parent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='budgetitem',
            options={},
        ),
        migrations.AlterField(
            model_name='budgetitem',
            name='code',
            field=models.CharField(max_length=50, verbose_name='code'),
        ),
        migrations.AlterUniqueTogether(
            name='budgetitem',
            unique_together={('user', 'code')},
        ),
    ]
