# Generated by Django 4.2.5 on 2023-09-28 00:26

import budget_flow_app.models
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget_flow_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budgetflow',
            name='months',
        ),
        migrations.AlterField(
            model_name='budgetflow',
            name='amount_per_month',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), null=True, size=12, validators=[budget_flow_app.models.validate_array_floats]),
        ),
    ]
