# Generated by Django 4.1.2 on 2023-06-28 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_alter_school_institutional_mail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='dane_code',
            field=models.CharField(max_length=100, verbose_name='dane code'),
        ),
    ]
